version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8000:8000'
    command:
      - start #start the SurrealDB server
      - --user
      - root #default user
      - --pass
      - root #default password
    restart: always
    volumes:
      - ./data/database.db:/database.db
  
  bot:
    build: .
    

